### ISSUE TITLE
Chnage UI of cards and make it like university official logos

### ISSUE THREAD

**Issue by TejasMishr** [TejasMishr/MMMUTRESO_OpenSource#12]
currently users are facing issue in too much scrolling.
make a ui like official website cards so that they can easily be accessible

**Comment by AdityaGaur7** [comment]
ok
plz assign

**Comment by TejasMishr** [comment]
okay i am also fixing it we both will fix it

**Comment by AdityaGaur7** [comment]
all cards are changed to UI like official mmmut website 
a new section si added aside of events

**Comment by TejasMishr** [comment]
okk
